#!/usr/bin/env python

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

import subprocess, urllib

def run():
	print 'reading package list from opkg'
	p = subprocess.Popen(['/usr/bin/opkg', 'list-installed'], stdout=subprocess.PIPE)
	packages = p.communicate()[0]
	print len(packages)
	print 'posting to submission url'
	formData = urllib.urlencode({"installed-package-list" : packages})
	f = urllib.urlopen("http://192.168.0.200/~tim/pop/popularity.php", formData)
	print 'done'

if __name__ == "__main__":
	run()
